server:
  port: 7070
proxy:
  loginUrl: http://10.47.197.13:7070/api/v1/user/login
plats:
  cookieMaps: {dataPin : dpc, quickBi: qbc}
  platMaps: {dataPin : http://baidu.com, quickBi: http://10.48.236.251:83}
  expireTimeMaps: {dataPin : 3600, quickBi: 3600}
newland:
  loginUrl: http://ip:port/path
  authUrl: http://10.48.134.112:32005/nl-edc-cct-system/v1/sso
  sigUserUrl: http://10.48.134.112:32005/nl-edc-cct-system/v1/qryUser
  allUserUrl: http://10.48.134.112:32005/nl-edc-cct-system/v1/qryTenant
