server:
  port: 8080
proxy:
  loginUrl: http://localhost:8080/api/v1/user/login
plats:
  cookieMaps: {dataPin : dpc, quickBi: qbc}
  platMaps: {dataPin : http://baidu.com, quickBi: http://163.com}
  expireTimeMaps: {dataPin : 3600, quickBi: 3600}
newland:
  loginUrl: http://ip:port/path
  authUrl: http://localhost:8080/api/v1/user-test/auth
  sigUserUrl: http://localhost:8080/api/v1/user-test/siguv
  allUserUrl: http://localhost:8080/api/v1/user-test/alluv
