debug: true
server:
  port: 7070
proxy:
  loginUrl: http://a.yidong.com:7070/api/v1/user/login
plats:
  cookieMaps: {dataPin : dpc, quickBi: qbc}
  platMaps: {dataPin : http://b.yidong.com:8088/, quickBi: http://b.yidong.com:8088/}
  expireTimeMaps: {dataPin : 3600, quickBi: 3600}
newland:
  loginUrl: http://ip:port/path
  authUrl: http://a.yidong.com:7070/api/v1/user-test/auth
  sigUserUrl: http://a.yidong.com:7070/api/v1/user-test/siguv
  allUserUrl: http://a.yidong.com:7070/api/v1/user-test/alluv
